shubhanshu23/DCIT-EDS

- blocks/footer-menu/footer-menu.css
- blocks/footer-menu/footer-menu.js
Fix: footer Navigation block create
Test URLs:
- Before: https://main--dcit-eds--shubhanshu23.aem.page/fragments/footer-menu
- After: https://footer-block--dcit-eds--shubhanshu23.aem.page/fragments/footer-menu
> footer block added

- blocks/footer-menu/footer-menu.css
> css changes

- component-models.json
> text component and properties added

- blocks/footer/footer.css
footer UI changes added the columns and css changes
> footer UI changes

- component-models.json
> added class in section to indentify plans section

- blocks/cards/cards.css
- component-filters.json
- component-models.json
> css changes for plans section cards

- component-definition.json
- component-filters.json
- component-models.json
> rte and container components added

- component-definition.json
- component-models.json
> rte and container components changes

- component-definition.json
- component-filters.json
- component-models.json
> Add pdf viewer

- blocks/cards/cards.css
> plan cards css changes

- models/_form.json
> form model added

- head.html
> script added in head

- blocks/login/login.css
- blocks/login/login.js
- component-definition.json
- component-filters.json
- component-models.json
Fix #
Test URLs:
- After:[ https://<branch>--{repo}--{owner}.aem.live/](https://feature-login-block--dcit-eds--shubhanshu23.hlx.page/#)
> Added login block

- blocks/quiz-question/quiz-question.css
- blocks/quiz-question/quiz-question.js
- component-definition.json
- component-models.json
> quiz question block prog

- .eslintrc.js
- blocks/quiz-question/quiz-question.css
- blocks/quiz-question/quiz-question.js
- component-models.json
> quiz question block created

- blocks/quiz-question/quiz-question.css
> quiz question block css changes

- blocks/quiz-form/quiz-form.css
- blocks/quiz-form/quiz-form.js
- blocks/quiz-question/quiz-question.css
- blocks/quiz-question/quiz-question.js
> quiz logic prog

- blocks/quiz-form/quiz-form.js
- blocks/quiz-question/quiz-question.js
- component-models.json
> quiz and form logic prog

- blocks/quiz-question/quiz-question.js
- component-models.json
> quiz score logic

- blocks/quiz-question/quiz-question.js
- blocks/quiz-score/quiz-score.css
- blocks/quiz-score/quiz-score.js
> quiz score opt

- blocks/quiz-last-form/quiz-last-form.css
- blocks/quiz-last-form/quiz-last-form.js
> quiz last form lint issues

- blocks/columns/columns.css
- component-models.json
> plan section UI changes

- blocks/quiz-form/quiz-form.css
- blocks/quiz-form/quiz-form.js
> quiz start btn handling

- blocks/right-plan/right-plan.css
- blocks/right-plan/right-plan.js
> right plan

- blocks/quiz-form/quiz-form.css
- blocks/quiz-form/quiz-form.js
> email otp handling

- blocks/header/header.css
- blocks/hero/hero.css
> header responsive changes- submenu

- blocks/footer/footer.css
- blocks/footer/footer.js
- component-models.json
Fix #75
Test URLs:
- Before: https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/login
- After: https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/login
> Adding cookie consent functionality

- blocks/footer/footer.js
Fix #75 
Test URLs:
- Before: https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/
- After: https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/
> changing from cookie to local storage

- blocks/footer/footer.js
Fix #76 
Test URLs:
- Before: https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/
- After: [https://<branch>--{repo}--{owner}.aem.live/](https://loginfunctionality--dcit-eds--shubhanshu23.aem.page/)
> asyncronous call for consent screen

- blocks/right-plan/right-plan.css
- blocks/right-plan/right-plan.js
> calculators UI update

- blocks/download/download.js
- component-models.json
> download page changes

- blocks/right-plan/right-plan.css
- blocks/right-plan/right-plan.js
> calc premium logic

- blocks/webinar/webinar.css
- blocks/webinar/webinar.js
- component-models.json
> webinar prog

- blocks/webinar/webinar.js
> webinar conf message

- blocks/quiz-form/quiz-form.js
- blocks/webinar/webinar.css
- blocks/webinar/webinar.js
- scripts/datalayer.js
> webinar otp funcitonality added
